---
version: "2"
services:

# Creating plex container

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - $HOME/containers/plex-rtorrent/plex:/config
      - /mnt/usb2/series:/data/tvshows
      - /mnt/usb2/movies:/data/movies
      - /mnt/usb2/music:/data/music
      - /mnt/usb2/Basket:/data/basquet
      - /mnt/usb2/Anime:/data/anime
    restart: unless-stopped


# Creating rutorrent container

  rutorrent:
    image: linuxserver/rutorrent
    container_name: rutorrent
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - $HOME/containers/plex-rtorrent/rtorrent:/config
      - /mnt/usb2/downloads:/downloads
    ports:
      - 8280:80
      - 5000:5000
      - 51413:51413
      - 6881:6881/udp
    restart: unless-stopped

# Tautulli container for monitoring, analytics and notification

  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Buenos_Aires
    volumes:
      - $HOME/containers/plex-rtorrent/tautulli:/config
      - $HOME/containers/plex-rtorrent/plex/logs:/logs
    ports:
      - 8181:8181
    restart: unless-stopped

