---
version: "2"
services:

# Creating plex container

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - $HOME/containers/plex:/config
      - /data/series:/data/tvshows
      - /data/movies:/data/movies
      - /data/music:/data/music
    restart: unless-stopped


# Creating rutorrent container

  rutorrent:
    image: linuxserver/rutorrent
    container_name: rutorrent
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - $HOME/containers/rtorrent:/config
      - /data/downloads:/downloads
    ports:
      - 8280:80
      - 5000:5000
      - 51413:51413
      - 6881:6881/udp
    restart: unless-stopped

# Tautulli container for monitoring, analytics and notification

  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Buenos_Aires
    volumes:
      - path to data:/config
      - path to plex logs:/logs
    ports:
      - 8181:8181
    restart: unless-stopped